name: Despliegue en Azure

on: [workflow_dispatch]

jobs:
  fake:
    runs-on: ubuntu-latest
    steps:
      - name: faking
        run: echo "faking a job to take a time"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "index.html,css/,imgs/"
          target: "/var/www/html"
